### ISSUE TITLE
markus issue

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/mbbefd#1]
Hi Giorgio,

I run into a problem with the function mbbefdExposure. It doesn’t seem to like parameter of c>4.1, in particular I can’t reproduce the Lloyd’s curve (c=5):

mbbefdExposure(0.5, b=swissRe(5.0)['b'], g=swissRe(5.0)['g'])
  b 
NaN 
Warning messages:
1: In log(a + b^x) : NaNs produced
2: In log(a + b) : NaNs produced

I ended up writing the following function, taken from the Bernegger paper:

mbbefdCurve <- function(x, C){
  g <- exp((0.78 + 0.12_C)_C)
  b <- exp(3.1 - 0.15_(1+C)_C) 
  if(identical(g, 1) | identical(b, 0))
    x
  if(identical(b, 1) & g > 1)
    log(1+(g-1)_x)/log(g)
  if(identical(b_g, 1) & g>1)
    (1-b^x)/(1-b)
  else
    log(((g-1)_b + (1-g_b)_b^x)/(1-b))/log(g_b)
}

**Comment by spedygiorgio** [comment]
Should be closed now

**Comment by mages** [comment]
I have added further checks, see: https://github.com/spedygiorgio/mbbefd/commit/df981c1ebf1aede7c2fb2dba523a0faaea5cc284
