### ISSUE TITLE
bug from new release of fitdistrplus

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/mbbefd#2]
Maybe it has been already solved btw I copy and paste

Dear maintainer,

Presumably following a recent update of 'fitdistrplus', we now see
- checking R code for possible problems ... NOTE
  fitDR: warning in mledist(x, distr = "mbbefd", start =
  initparmbbefd[[1]], custom.optim = constrOptim.nl, hin =
  constrmbbefd1, control.outer = list(trace = FALSE), gr = grLL):
  partial argument match of ‘gr’ to ‘gradient’
  fitDR: warning in mledist(x, distr = "mbbefd", start =
  initparmbbefd[[2]], custom.optim = constrOptim.nl, hin =
  constrmbbefd2, control.outer = list(trace = FALSE), gr = grLL):
  partial argument match of ‘gr’ to ‘gradient’
- checking examples ... ERROR
  Running examples in ‘mbbefd-Ex.R’ failed
  The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: fitDR
> ### Title: Fit of destruction rate models
> ### Aliases: fitDR
> ### Keywords: distribution
> ### *\* Examples
> # (1) fit of a one-inflated beta distribution by maximum likelihood estimation
> # 
> 
> n <- 1e3
> set.seed(12345)
> x <- roibeta(n, 3, 2, 1/6)
> 
> f1 <- fitDR(x, "oibeta", method="mle")
> Warning in cbind(as.matrix(f1$vcov), rep(0, npar - 1)) :
>   number of rows of result is not a multiple of vector length (arg 2)
> Warning in rbind(cbind(as.matrix(f1$vcov), rep(0, npar - 1)), c(rep(0, npar -  :
>   number of columns of result is not a multiple of vector length (arg 2)
> Error in fitDR(x, "oibeta", method = "mle") : 
>   length of 'dimnames' [1] not equal to array extent
> Execution halted
> - checking for unstated dependencies in ‘tests’ ... OK
> - checking tests ... ERROR
>   Running the tests in ‘tests/test-beaonre.R’ failed.
>   Last 13 lines of output:
>   [1] "oistpareto"
>   [1] "oibeta"
>   Error in fitDR(x, d, method = "mle") : 
>     length of 'dimnames' [1] not equal to array extent
>   Calls: lapply -> FUN -> fitDR
>   In addition: Warning messages:
>   1: In mledist(data, distname, start, fix.arg, ...) :
>     The BFGS method cannot be used with bounds without provided the gradient. The method is changed to L-BFGS-B.
>   2: In cov2cor(f1$vcov) :
>     diag(.) had 0 or NA entries; non-finite result is doubtful
>   3: In cbind(as.matrix(f1$vcov), rep(0, npar - 1)) :
>     number of rows of result is not a multiple of vector length (arg 2)
>   4: In rbind(cbind(as.matrix(f1$vcov), rep(0, npar - 1)), c(rep(0, npar -  :
>     number of columns of result is not a multiple of vector length (arg 2)
>   Execution halted
> - checking for unstated dependencies in vignettes ... OK
> - checking package vignettes in ‘inst/doc’ ... OK
> - checking re-building of vignette outputs ... WARNING
>   Error in re-building vignettes:
>   ...
>   Loading required package: fitdistrplus
>   Loading required package: MASS
>   Loading required package: survival
>   Loading required package: alabama
>   Loading required package: numDeriv
>   Package:  mbbefd
>   Version:  0.8-0
>   Date:    2016-02-23 22:30:54
>   BugReport: http://github.com/spedygiorgio/mbbefd/issues

Warning in cbind(as.matrix(f1$vcov), rep(0, npar - 1)) :
  number of rows of result is not a multiple of vector length (arg 2)
Warning in rbind(cbind(as.matrix(f1$vcov), rep(0, npar - 1)), c(rep(0, npar -  :
  number of columns of result is not a multiple of vector length (arg 2)
Quitting from lines 682-688 (Introduction_to_mbbefd.Rmd) 
Error: processing vignette ‘Introduction_to_mbbefd.Rmd’ failed with diagnostics:
length of ‘dimnames’ [1] not equal to array extent
Execution halted

**Comment by dutangc** [comment]
Update is done on github. The only thing to do is to merge ChangeLog and NEWS files. 

You can submit a new version on CRAN.

## CD

Christophe Dutang
LMM, UdM, Le Mans, France
web: http://dutangc.free.fr http://dutangc.free.fr/

**Comment by spedygiorgio** [comment]
Thank you very much 

Sent from my ASUS

-------- Messaggio originale --------
Da:Christophe Dutang notifications@github.com
Inviato:Thu, 07 Jul 2016 13:41:11 +0200
A:spedygiorgio/mbbefd mbbefd@noreply.github.com
Cc:Giorgio Alfredo Spedicato spedygiorgio@gmail.com,Author author@noreply.github.com
Oggetto:Re: [spedygiorgio/mbbefd] bug from new release of fitdistrplus (#2)

> Update is done on github. The only thing to do is to merge ChangeLog and NEWS files. 
> 
> You can submit a new version on CRAN.
> 
> ## CD
> 
> Christophe Dutang
> LMM, UdM, Le Mans, France
> web: http://dutangc.free.fr http://dutangc.free.fr/
>

**Comment by spedygiorgio** [comment]
On CRAN now
