### ISSUE TITLE
checking formula

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/mbbefd#4]
Hello

Thank you for the great package.

I think the formula for G(x) in 2.1.2 within https://cran.r-project.org/web/packages/mbbefd/vignettes/Introduction_to_mbbefd.pdf isn’t correct.

The correct formula, when reduced, is I think B(x,a+1,b)+x*(a+b)/a*(1-B(x,a,))

**Comment by dutangc** [comment]
The formula (in the pdf) is now corrected. See attached file for details:
[checkbeta.pdf](https://github.com/spedygiorgio/mbbefd/files/1925267/checkbeta.pdf)

Note that the R code was correct.
