### ISSUE TITLE
port all function to roxygen2

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/mbbefd#5]
Hi, Cran says:
so I would move all the help into roxygen2 files.

Dear maintainers,

This concerns CRAN packages maintained by one of you, see the long list
at the end of this message.

These packages document package metadata (specifically, package
versions) in their *-package Rd file(s) which have gotten out of sync
with the actual package metadata in the DESCRIPTION file.

Most likely, these Rd files were generated by older versions of
utils::promptPackage() (maybe via utils::package.skeleton()), which
generated package documentation shells/skeletons with copies of the
current package metadata.  This was not a good idea, as inevitably such
copies go out of sync with their master values.  The R 3.2.0 release
(3 years ago) did

  A number of macros have been added in the new 'share/Rd' directory for
  use in package overview help pages, and promptPackage() now makes use
  of them.

(so that package documentation shells/skeletons generated with current
versions of utils::promptPackage() use Rd macro references to the
package metadata values instead of making copies).

Can you please bring package Rd files "up to date"?  The simplest may be
using a current utils::promptPackage() to re-generate the
shell/skeleton, and merge with the content of the current package Rd
file.  (In case the updated package Rd file would more or less only
duplicate the package metadata, feel free to drop the package Rd file
from your package sources.)

Best
-k

**Comment by dutangc** [comment]
Ok. We will do this during the summer.

------------------------------------------------------------
Christophe Dutang
CEREMADE, Univ. Paris Dauphine, France
Web : http://dutangc.free.fr
------------------------------------------------------------

**Comment by spedygiorgio** [comment]
thanks @dutangc

**Comment by dutangc** [comment]
Dear Giorgio,

I have just updated mbbefd package to take into account
- metadata of ?mbbefd
- remove g argument in <d,p,q>mbbefd()
- update starting values 

If you agree, we could submit a new version before the end of Summer. I need that new version to release new version of fitdistrplus.

Have a nice holiday

Regards, Christophe

------------------------------------------------------------
Christophe Dutang
CEREMADE, Univ. Paris Dauphine, PSL Univ., France
Web : http://dutangc.free.fr
------------------------------------------------------------
