### ISSUE TITLE
add orcid link

### ISSUE THREAD

**Issue by spedygiorgio** [spedygiorgio/mbbefd#6]
Hi all,
it could be nice to add  ORCID links if you have one  [R-Bloggers on Orcid](https://www.r-bloggers.com/distinguish-yourself-in-cran-person-with-orcid/)

**Comment by dutangc** [comment]
Ok. I make a small commit yesterday btw.

------------------------------------------------------------
Christophe Dutang
CEREMADE, Univ. Paris Dauphine, PSL Univ., France
Web : http://dutangc.free.fr
------------------------------------------------------------

**Comment by spedygiorgio** [comment]
Hi @dutangc do we need to submit a new version to CRAN?

**Comment by spedygiorgio** [comment]
@dutangc  added also yours. Please check
